import Link from "next/link";
import { Search } from "lucide-react";
import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { BookStatusSelect } from "@/components/admin/book-status-select";
import { getAdminBooks } from "@/lib/admin/queries";

const filters = [["all", "Все"], ["writing", "Написание"], ["editing", "Редактура"], ["printing", "Печать"], ["ready", "Готово"], ["delivery", "Доставка"], ["received", "Получен"]];
export default async function AdminBooksPage({ searchParams }: { searchParams: Promise<{ status?: string; q?: string }> }) {
  const { status = "all", q = "" } = await searchParams;
  const needle = q.trim().toLowerCase();
  const books = (await getAdminBooks()).filter(book => (status === "all" || book.status === status) && (!needle || `${book.title} ${book.authorName} ${book.ownerName} ${book.ownerPhone}`.toLowerCase().includes(needle)));
  return <><DashboardHeader title="Книги" description="Все книги пользователей и этапы их производства" /><section className="admin-card admin-list-card"><header><nav className="admin-tabs">{filters.map(([value, label]) => <a className={status === value ? "is-active" : ""} key={value} href={`/admin/books?status=${value}`}>{label}</a>)}</nav></header><form className="admin-search"><Search size={17} /><input name="q" aria-label="Поиск" defaultValue={q} placeholder="Поиск по книге, автору или пользователю" /><input type="hidden" name="status" value={status} /></form><div className="admin-table-wrap" tabIndex={0} role="region" aria-label="Таблица данных — прокрутите для просмотра всех столбцов"><table className="admin-table"><thead><tr><th>Книга</th><th>Пользователь</th><th>Прогресс</th><th>Создана</th><th>Статус</th></tr></thead><tbody>{books.map(book => <tr key={book.id}><td><Link className="admin-book-link" href={`/admin/books/${book.id}`}>{book.title}</Link><small>Автор: {book.authorName} · Для: {book.recipientName}</small></td><td><b>{book.ownerName}</b><small>{book.ownerPhone}</small></td><td><div className="admin-book-progress"><span><i style={{ width: `${book.progress}%` }} /></span><b>{book.progress}%</b></div></td><td>{new Date(book.createdAt).toLocaleDateString("ru-KZ")}</td><td><BookStatusSelect bookId={book.id} status={book.status} /></td></tr>)}{books.length === 0 && <tr><td className="admin-table-empty" colSpan={5}><strong>Книг не найдено</strong><span>{q ? "Попробуйте изменить поисковый запрос." : status === "all" ? "Книга появится здесь сразу после того, как пользователь создаст её в личном кабинете." : "На выбранном этапе пока нет книг."}</span></td></tr>}</tbody></table></div></section></>;
}
